steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x deploy_proxy.sh
        ./deploy_proxy.sh qrec-qa-apigee-nonprod uat qrec-qa-apigee-prod prod

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
