steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set source and destination project IDs and environments
        SOURCE_PROJECT="qrec-qa-apigee-nonprod"
        DEST_PROJECT="qrec-qa-apigee-prod"
        SOURCE_ENV="uat"
        DEST_ENV="prod"
        
        # List all proxies in the source environment
        PROXIES=$(gcloud apigee apis list --project=qrec-qa-apigee-nonprod --environment=uat --format="value(name)")

        # Loop through each proxy and export, then import to the destination project and environment
        for PROXY_NAME in $PROXIES; do
          echo "Processing proxy: $PROXY_NAME"
          
          # Export the proxy
          gcloud apigee apis export --project=qrec-qa-apigee-nonprod --environment=uat --api=$PROXY_NAME --output="${PROXY_NAME}.zip"
          
          # Import the proxy to the destination project
          gcloud apigee apis import --project=qrec-qa-apigee-prod --environment=prod --api=$PROXY_NAME --file="${PROXY_NAME}.zip"
          
          echo "Uploaded proxy: $PROXY_NAME to project: qrec-qa-apigee-prod environment: prod"
        done

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
