steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set source and destination project IDs and environments
        SOURCE_PROJECT="qrec-qa-apigee-nonprod"
        DEST_PROJECT="qrec-qa-apigee-prod"
        SOURCE_ENV="uat"
        DEST_ENV="prod"
        
        # Authenticate with gcloud (ensure the service account key is set correctly)
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

        # Loop through each proxy and export, then import to the destination project and environment
        gcloud apigee apis list --project=qrec-qa-apigee-nonprod --environment=uat --format="value(name)" |
        while read -r PROXY; do
          echo "Processing proxy: $PROXY"
          
          # Export the proxy
          gcloud apigee apis export --project=qrec-qa-apigee-nonprod --environment=uat --api=$PROXY --output="${PROXY}.zip"
          
          # Import the proxy to the destination project
          gcloud apigee apis import --project=qrec-qa-apigee-prod --environment=prod --api=$PROXY --file="${PROXY}.zip"
          
          echo "Uploaded proxy: $PROXY to project: qrec-qa-apigee-prod environment: prod"
        done

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
