steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Set source and destination project IDs and environments
        SOURCE_PROJECT="qrec-qa-apigee-nonprod"
        DEST_PROJECT="qrec-qa-apigee-prod"
        SOURCE_ENV="uat"
        DEST_ENV="prod"
        
        # Authenticate with gcloud
        # gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

        # List all proxies in the source environment
        PROXIES=$(gcloud apigee apis list --project=$SOURCE_PROJECT --environment=$SOURCE_ENV --format="value(name)")

        # Loop through each proxy and export, then import to the destination project and environment
        for PROXY in $PROXIES; do
          echo "Processing proxy: $PROXY"
          
          # Export the proxy
          gcloud apigee apis export --project=$SOURCE_PROJECT --environment=$SOURCE_ENV --api=$PROXY --output="${PROXY}.zip"
          
          # Import the proxy to the destination project
          gcloud apigee apis import --project=$DEST_PROJECT --environment=$DEST_ENV --api=$PROXY --file="${PROXY}.zip"
          
          echo "Uploaded proxy: $PROXY to project: $DEST_PROJECT environment: $DEST_ENV"
        done

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
