steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars

  - name: 'gcr.io/cloud-builders/curl'
    id: create-kvm
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        curl -X POST -H "Authorization: Bearer $build_token" \
             -H "Content-Type: application/json" \
             -d '{
                   "name": "apiegee-test-kvm",
                   "encrypted": false,
                   "entry": [
                     {
                       "name": "name1",
                       "value": "vikram"
                     },
                     {
                       "name": "name2",
                       "value": "vicky"
                     }
                   ]
                 }' \
             "https://apigee.googleapis.com/v1/organizations/qrec-qa-apigee-nonprod/environments/dev/keyvaluemaps"

timeout: '600s'
