steps:
  # Step 1: Get an authentication token and store it in a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars

  # Step 2: Fetch the KVM details from the dev environment
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-X'
      - 'GET'
      - 'https://apigee.googleapis.com/v1/organizations/ORGANIZATION_ID/environments/dev/keyvaluemaps/apigee-internal-devops-01'
      - '-H'
      - 'Authorization: Bearer $(cat /workspace/build_vars | grep build_token | cut -d= -f2)'

  # Step 3: Deploy the fetched KVM to the dev-int environment
  - name: 'gcr.io/cloud-builders/curl'
    args:
      - '-X'
      - 'POST'
      - 'https://apigee.googleapis.com/v1/organizations/ORGANIZATION_ID/environments/dev-int/keyvaluemaps'
      - '-H'
      - 'Authorization: Bearer $(cat /workspace/build_vars | grep build_token | cut -d= -f2)'
      - '-H'
      - 'Content-Type: application/json'
      - '-d'
      - |
        {
          "name": "apigee-internal-devops-01",
          "encrypted": false,  # Adjust as per your encryption requirements
          "entry": [
            {
              "name": "key1",
              "value": "value1"
            },
            {
              "name": "key2",
              "value": "value2"
            }
            # Add more key-value pairs as needed
          ]
        }
