steps:
  # Step 1: Get an authentication token and store it in a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars

  # Step 2: Create KVM using the script
  - name: 'gcr.io/cloud-builders/docker'
    id: "Create KVM"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Creating KVM in dev environment..."
        bash create_kvm.sh
