steps:
  # Step 1: Get an authentication token and store it in a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token=\"$(gcloud auth application-default print-access-token)\"
        env | grep "^build_" > /workspace/build_vars

  # Step 2: Deploy the KVM from dev to dev-int in Apigee
  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy KVM Bundle"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying KVM from dev to dev-int in Apigee..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/environments/${_APIGEE_UAT_ENV}/keyvaluemaps" \
        -H "Authorization: Bearer ${build_token}" \
        -H "Content-Type: application/json" \
        -d '{
          "name": "apigee-internal-01",
          "encrypted": false,
          "entry": [
            {
              "name": "key1",
              "value": "value1"
            },
            {
              "name": "key2",
              "value": "value2"
            }
          ]
        }'
