steps:
  # Step 0: Make create_kvm.sh executable
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - -c
      - |
        chmod +x deploy-apigee-kvm/create_kvm.sh

  # Step 1: Execute create_kvm.sh script
  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-kvm-script
    entrypoint: 'bash'
    args:
      - -c
      - |
        ./deploy-apigee-kvm/create_kvm.sh

  # Step 2: Get authentication token and store it in a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars
