steps:
  # Step 1: Get an authentication token and store it in a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars

  # Step 2: Retrieve the existing KVM data from the dev environment
  - name: 'gcr.io/cloud-builders/curl'
    id: "Retrieve KVM Bundle"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Retrieving KVM from dev environment..."
        curl -X GET "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/environments/dev/keyvaluemaps/apigee-internal-devops-01" \
        -H "Authorization: Bearer ${build_token}" \
        -H "Accept: application/json" \
        -o /workspace/kvm_data.json

  # Step 3: Deploy the retrieved KVM data to the dev-int environment
  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy KVM Bundle"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying KVM to dev-int environment..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/environments/dev-int/keyvaluemaps" \
        -H "Authorization: Bearer ${build_token}" \
        -H "Content-Type: application/json" \
        -d @/workspace/kvm_data.json
