steps:
  # Step 1: Get an authentication token and store it in a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars

  # Step 2: Create a sample KVM with a few name-value pairs and deploy it to the dev environment
  - name: 'gcr.io/cloud-builders/curl'
    id: "Create KVM"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Creating KVM in dev environment..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/environments/dev/keyvaluemaps" \
        -H "Authorization: Bearer ${build_token}" \
        -H "Content-Type: application/json" \
        -d '{
            "name": "SampleKVM",
            "entry": [
                {
                    "name": "COMPANY",
                    "value": "example.com"
                },
                {
                    "name": "LOCATION",
                    "value": "San Francisco"
                }
            ]
        }'
