steps:
  # Step 1: Retrieve Google Auth Token
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-auth-token'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the auth token
        export build_token=\"$(gcloud auth print-access-token)\"
        echo "build_token=${build_token}" > /workspace/auth-token.txt

  # Step 2: Export the specific product
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Source substitution variables
        source_org="qrec-qa-apigee-nonprod"
        source_product_name="apigee-internal-devops"
        output_dir="/workspace/product"
        mkdir -p ${output_dir}
        
        # Read the token from the previous step
        source /workspace/auth-token.txt
        
        # Export the specified product
        echo "Exporting product: ${source_product_name}"
        curl -H "Authorization: Bearer ${build_token}" https://apigee.googleapis.com/v1/organizations/${source_org}/apiproducts/${source_product_name} -o ${output_dir}/${source_product_name}.json
       
  # Step 3: Push the exported product to GitHub Repo
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Source substitution variables
        git_username="vikrammaddirala"
        git_userpassword="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"
        git_usermail="vikram.maddirala5@gmail.com"
        git_reponame="qrec"
        source_product_name="apigee-internal-devops"
        target_product_name="apigee-internal-devops"
        
        ssh-keyscan -t rsa github.com > known_hosts.github
        cp known_hosts.github known_hosts
        echo "cloning the repo.."
        git clone https://${git_username}:${git_userpassword}@github.com/${git_username}/${git_reponame}.git
        echo "list repo directory"
        cd ${git_reponame}/
        git status
        git config --global user.email "${git_usermail}"
        git config --global user.name "${git_username}"
        echo "list repo files"
        ls
        echo "copy ${target_product_name}.json"
        cp /workspace/product/${source_product_name}.json export-import-product/import-product/${target_product_name}.json
        git add .
        git commit -m "adding product ${target_product_name}.json"
        echo "Commit & Push the file into repo.."
        git push https://${git_username}:${git_userpassword}@github.com/${git_username}/${git_reponame}.git
