steps:
  # Step 1: Undeploy the shared flow from the dev-int environment if already deployed
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Undeploy Shared Flow (if exists)'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -X DELETE "https://apigee.googleapis.com/v1/organizations/$PROJECT_ID/environments/dev-int/sharedflows/$SHARED_FLOW_NAME/revisions/$REVISION_NUMBER/deployments" \
        -H "Authorization: Bearer $(gcloud auth print-access-token)" || true

  # Step 2: Deploy the shared flow to the dev-int environment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Deploy Shared Flow'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -X POST "https://apigee.googleapis.com/v1/organizations/$PROJECT_ID/environments/dev-int/sharedflows/$SHARED_FLOW_NAME/revisions/$REVISION_NUMBER/deployments" \
        -H "Authorization: Bearer $(gcloud auth print-access-token)"

substitutions:
  _PROJECT_ID: 'YOUR_PROJECT_ID'
  _SHARED_FLOW_NAME: 'YOUR_SHARED_FLOW_NAME'
  _REVISION_NUMBER: 'YOUR_REVISION_NUMBER'
