steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: "Deploy Proxy Bundle"
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Deploying proxy from dev to dev-int in Apigee..."
        gcloud apigee deployments create --name=helloworld --source=dev --environment=dev-int

substitutions:
  _PROJECT_ID: 'qrec-qa-apigee-nonprod'
