steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars

  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy Proxy Bundle"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying proxy from dev to dev-int in Apigee..."
        response=$(curl -s -X POST "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/environments/${_APIGEE_UAT_ENV}/apis/helloworld-test/revisions/1/deployments" \
        -H "Authorization: Bearer ${build_token}")

        if echo "$response" | grep -q "404 Not Found"; then
          echo "404 Not Found: Deployment failed."
          # Perform additional actions or exit with an error code
        else
          echo "Deployment successful."

          # Extract and display deployment details without jq
          echo "Deployment Details:"
          echo "$response" | grep -E 'environment|apiProxy|revision|deployStartTime|proxyDeploymentType'

          # Add the proxy to the product
          product_response=$(curl -s -X PATCH "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/apiproducts/apigee-internal-devops" \
          -H "Authorization: Bearer ${build_token}" \
          -H "Content-Type: application/json" \
          -d '{
                "operation": "add",
                "path": "/proxies",
                "value": "helloworld-test"
              }')

          echo "Product Update Response:"
          echo "$product_response"
        fi
