steps:
  # Step 1: Deploy the existing proxy revision to the dev-int environment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Proxy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth print-access-token > access_token.txt
        curl -X POST -H "Authorization: Bearer $(cat access_token.txt)" \
        -H "Content-Type: application/json" \
        -d '{"name":"helloworld", "revision":"1", "environment":"dev-int"}' \
        "https://apigee.googleapis.com/v1/organizations/qrec-qa-apigee-nonprod/environments/dev-int/apis/helloworld/revisions/1/deployments"

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
