steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        env | grep "^build_" > /workspace/build_vars

  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy Proxy Bundle"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying proxy from dev to dev-int in Apigee..."
        response=$(curl -s -X POST "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/environments/${_APIGEE_UAT_ENV}/apis/helloworld-test/revisions/1/deployments" \
        -H "Authorization: Bearer ${build_token}")

        if echo "$response" | grep -q "404 Not Found"; then
          echo "404 Not Found: Deployment failed."
          exit 1
        else
          echo "Deployment successful."
        fi

  - name: 'gcr.io/cloud-builders/curl'
    id: "Test Proxy"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Testing the deployed proxy..."
        proxy_response=$(curl -s -X GET "https://YOUR_PROXY_ENDPOINT_URL" \
        -H "Authorization: Bearer ${build_token}")

        echo "Response from the deployed proxy:"
        echo "$proxy_response"

        if echo "$proxy_response" | grep -q "expected_response"; then
          echo "Proxy is working as expected."
        else
          echo "Proxy response is not as expected."
          exit 1
        fi
