steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token=\"$(gcloud auth application-default print-access-token)\"
        env | grep "^build_" > /workspace/build_vars

  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy Proxy Bundle"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying proxy to Apigee test environment..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/apis?action=import&name=helloworld" \
        -H "Authorization: Bearer ${build_token}" \
        -F "file=@/workspace/proxy.zip"
        curl -X POST "https://apigee.googleapis.com/v1/organizations/apigee-x-379708/environments/${_APIGEE_UAT_ENV}/apis/helloworld/revisions/1/deployments" \
        -H "Authorization: Bearer ${build_token}"

substitutions:
  _APIGEE_DEV_ENV: "dev"
  _APIGEE_UAT_ENV: "dev-int"
