steps:
  # Step 1: Export the proxy from the dev environment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Export Proxy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -X GET -H "Authorization: Bearer $ACCESS_TOKEN" \
        -o exported_proxy.zip \
        "https://apigee.googleapis.com/v1/organizations/qrec-qa-apigee-nonprod/environments/dev/apis/helloworld/revisions/1?format=bundle"
    secretEnv: ['ACCESS_TOKEN']

  # Step 2: Import the proxy to the dev-int environment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Import Proxy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" \
        -F file=@exported_proxy.zip \
        "https://apigee.googleapis.com/v1/organizations/qrec-qa-apigee-nonprod/apis?action=import&name=helloworld"
    secretEnv: ['ACCESS_TOKEN']

  # Step 3: Deploy the proxy to the dev-int environment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Deploy Proxy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"name":"helloworld", "revision":"1", "environment":"dev-int"}' \
        "https://apigee.googleapis.com/v1/organizations/qrec-qa-apigee-nonprod/environments/dev-int/apis/helloworld/revisions/1/deployments"
    secretEnv: ['ACCESS_TOKEN']

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
secrets:
  - kmsKeyName: projects/PROJECT_ID/locations/global/keyRings/KEY_RING/cryptoKeys/KEY_NAME
    secretEnv:
      ACCESS_TOKEN: ENCRYPTED_ACCESS_TOKEN
