steps:
  # Step 1: Export the proxy from the dev environment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Export Proxy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -X GET -H "Authorization: Bearer $(gcloud auth print-access-token)" \
        -o exported_proxy.zip \
        "https://apigee.googleapis.com/v1/organizations/qrec-qa-apigee-nonprod/environments/dev/apis/helloworld/revisions/1?format=bundle"

  # Step 2: Import the proxy to the dev-int environment
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Import Proxy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl -X POST -H "Authorization: Bearer $(gcloud auth print-access-token)" \
        -F file=@exported_proxy.zip \
        "https://apigee.googleapis.com/v1/organizations/qrec-qa-apigee-nonprod/apis?action=import&name=helloworld"

timeout: '3600s'

options:
  logging: CLOUD_LOGGING_ONLY
