steps:
  # Step 1: Retrieve Google Auth Token
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token=\"$(gcloud auth application-default print-access-token)\"
        env | grep "^build_" > /workspace/build_vars

  # Step 2: Install Apigee CLI and deploy the shared flow from dev to uat
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # install apigeecli
        echo "Installing apigeecli"
        source deploy-apigee-createapp/installapigeecli.sh

        # Source substitution variables
        shared_flow_name="commonSF_devops__v1"
        source_env="dev"
        target_env="uat"
        target_org="qrec-qa-apigee-nonprod"
        
        # Read the token from the previous step
        source /workspace/auth-token.txt
        
        # Deploy the shared flow from dev to uat environment
        echo "Deploying shared flow: ${shared_flow_name} from ${source_env} to ${target_env}"
        /usr/local/bin/apigeecli sharedflows deploy --name ${shared_flow_name} --fromenv ${source_env} --toenv ${target_env} --org ${target_org} --token ${build_token} --wait --ovr
