steps:
  # Step 1: Set Variables and Fetch Access Token
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token="$(gcloud auth application-default print-access-token)"
        echo "build_token=$build_token" > /workspace/build_vars

  # Step 2: Fetch Product Details from Dev Environment
  - name: 'gcr.io/cloud-builders/curl'
    id: "Fetch Product Details"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Fetching product details from dev environment..."
        curl -X GET "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/apiproducts/apigee-internal-devops" \
        -H "Authorization: Bearer ${build_token}" > /workspace/product_details.json

  # Step 3: Print Product Details for Debugging
  - name: 'gcr.io/cloud-builders/bash'
    id: "Print Product Details"
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Product details JSON:"
        cat /workspace/product_details.json

  # Step 4: Modify Product Details for Dev-Int Environment (if needed)
  - name: 'gcr.io/cloud-builders/bash'
    id: "Modify Product Details"
    entrypoint: 'bash'
    args:
      - -c
      - |
        # Modify the product details as needed for dev-int environment
        # Here you can add any jq commands to modify the JSON file
        cp /workspace/product_details.json /workspace/product_details_devint.json

  # Step 5: Print Modified Product Details for Debugging
  - name: 'gcr.io/cloud-builders/bash'
    id: "Print Modified Product Details"
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo "Modified product details JSON:"
        cat /workspace/product_details_devint.json

  # Step 6: Deploy Product to Dev-Int Environment
  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy Product"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying product to dev-int environment..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/apiproducts" \
        -H "Authorization: Bearer ${build_token}" \
        -H "Content-Type: application/json" \
        -d @/workspace/product_details_devint.json
