steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: variables
    entrypoint: 'bash'
    args:
      - -c
      - |
        export build_token=\"$(gcloud auth application-default print-access-token)\"
        env | grep "^build_" > /workspace/build_vars

  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy Shared Flow Bundle"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying shared flow from dev to dev-int in Apigee..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/environments/${_APIGEE_UAT_ENV}/sharedflows/commonSF_devops__v1/revisions/1/deployments" \
        -H "Authorization: Bearer ${build_token}"

  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy Product"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying product from dev to dev-int in Apigee..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/environments/${_APIGEE_UAT_ENV}/apiproducts/apigee-internal-devops" \
        -H "Authorization: Bearer ${build_token}"

  - name: 'gcr.io/cloud-builders/curl'
    id: "Deploy App"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Deploying app from dev to dev-int in Apigee..."
        curl -X POST "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/environments/${_APIGEE_UAT_ENV}/apps/internal-dev-devops" \
        -H "Authorization: Bearer ${build_token}"

  - name: 'gcr.io/cloud-builders/curl'
    id: "Add Proxy to Product"
    entrypoint: 'bash'
    args:
      - -c
      - |
        source /workspace/build_vars
        echo "Adding proxy to product in Apigee..."
        curl -X PATCH "https://apigee.googleapis.com/v1/organizations/${_APIGEE_PROJECT}/apiproducts/apigee-internal-devops" \
        -H "Authorization: Bearer ${build_token}" \
        -H "Content-Type: application/json" \
        -d '{"proxies": ["kvm_ops_v1"]}'
